#!/usr/bin/env python

import json
import requests
import sys
import os

# Get variables from config.
# Default to localhost:8080
try:
    host = os.environ['host']
except:
    host = 'localhost'

try:
    port = os.environ['port']
except:
    port = '8080'

if len(sys.argv) == 2 and sys.argv[1] == "autoconf":
    print 'yes'

elif len(sys.argv) == 2 and sys.argv[1] == "config":
    print 'graph_title PuppetDB Failed to Process'
    print 'graph_args --base 1000 -l 0'
    print 'graph_vlabel number fatal'
    print 'graph_category puppetdb'
    print 'graph_info This graph displays the number of failed commands.'
    print 'fatal.label puppetdb_fatal'
    print 'fatal.info Fatal PuppetDB runs.'

else:
    puppetdb_url = 'http://%s:%s/v2' % (host, port)
    headers = {'Accept': 'application/json'}
    call = requests.get(puppetdb_url + '/metrics/mbean/com.puppetlabs.puppetdb.command:type=global,name=fatal', headers=headers)
    data = json.loads(call.content)
    fatal_count = data['Count']

    print "fatal.value %d" % (fatal_count)
